### ISSUE TITLE
 INTRODUCE RANDOMNESS  [ROBUSTNESS]

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/simulating-risk#53] opened 2023-12-11 19:39 UTC
For example: each agent has a 0.01 chance of just playing DOVE and a 0.01 chance of just playing HAWK rather than using our standard procedure to determine what he plays.  (Or change these numbers, maybe make them higher?)

**Comment by rlskoeser** [comment] 2023-12-14 15:55
duplicate of #45 ; will keep that one and add the robustness label

**Closed by rlskoeser** 2023-12-14 15:55 UTC
Labels: Robustness
